User Fusion Rendering
networkteam/neos-mockup pull request #4
Opened 2020-02-05 14:55 UTC by nilsjung

This MR replaces the fluid template rendering with the fusion rendering aproach.

2020-02-07 11:58 UTC, suffle requested changes

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Components/Organisms/Navbar.fusion
> +    items = null
```suggestion
    items = ${[]}
```

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Components/Organisms/Navbar.fusion
> +    items = null
```suggestion
    items = ${[]}
```

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Components/Organisms/Navbar.fusion
> +    subitems = ''
```suggestion
    subitems = ${[]}
```

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Components/Molecules/Header.fusion
> +    mainNavigation = null
```suggestion
    mainNavigation = ''
```

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Components/Atoms/Placeholder.fusion
> +    placeholder = null
```suggestion
    placeholder = ''
```

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Content/Placeholder.fusion
> +        attributes = Neos.Fusion:DataStructure {
a lot of what is done here can also be done in the component itself, especially the style attribute should not be of any concern to the  mapping component

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Documents/Document.Menu.fusion
> +prototype(Networkteam.Neos.Mockup:Document.Menu) < prototype(Neos.Fusion:Value) {
If you use a `Neos.Fusion:Component` you dont have to push the api-values to the context manually

2020-02-07 11:58 UTC, suffle commented on Resources/Private/Fusion/Documents/Document.Menu.fusion
> +        condition = ${Array.indexOf(rootline, item) != -1}
Using a context variable, that is defined several steps above is always a bit hard to understand, maybe we should use a `Neos.Fusion:Component` here a s well and set the API explicitly

2020-02-07 14:32 UTC, nilsjung commented
I adjusted the menu to use `Neos.Fusion:Component` instead of `Neos.Fusion:Value` and changed the type of the default values.

2020-02-11 12:00 UTC, suffle requested changes

2020-02-11 12:00 UTC, suffle commented on Resources/Private/Fusion/Documents/Document.Menu.fusion
> +
Remove unnecessary new line

2020-02-11 12:00 UTC, suffle commented on Resources/Private/Fusion/Documents/Document.Menu.fusion
> +
Remove unnecessary new line

2020-02-11 12:04 UTC, suffle approved these changes

2020-02-11 15:09 UTC, merged